baseURL = "https://brandonstewart.net/"
title = "Brandon Stewart's Blog"
theme = "temple_updated"
publishDir = "docs"

[params]
  # Enables syntax highlighting
  highlight = true 
  # Supports highlighting for languages not included in the original pack
  # See https://highlightjs.org/download/
  hjslangs = ["go", "bash"]
  # Enables the topmenu, which pulls from categories
  topmenu = "categories"

# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "Brandon Stewart"
  github = "stwrt"
  email = "stewartb2@gmail.com"
  gaid = "UA-74293424-2"
